const API_BASE=(window.PDF_API_BASE_URL||"").replace(/\/$/,"");
const api=(path)=>API_BASE+path;
const tools=[
{id:"merge",icon:"⊕",title:"Merge PDF",desc:"Combine multiple PDFs into one file.",multi:true,accept:".pdf",endpoint:"/api/pdf/merge",tag:"Organize"},
{id:"split",icon:"✂",title:"Split PDF",desc:"Extract a page range into a new PDF.",accept:".pdf",endpoint:"/api/pdf/split",tag:"Organize"},
{id:"compress",icon:"↘",title:"Compress PDF",desc:"Reduce file size with a safe PDF rewrite.",accept:".pdf",endpoint:"/api/pdf/compress",tag:"Optimize"},
{id:"rotate",icon:"↻",title:"Rotate PDF",desc:"Rotate every page by 90, 180 or 270 degrees.",accept:".pdf",endpoint:"/api/pdf/rotate",tag:"Organize"},
{id:"delete",icon:"−",title:"Delete Pages",desc:"Remove selected pages from a PDF.",accept:".pdf",endpoint:"/api/pdf/delete-pages",tag:"Edit"},
{id:"extract",icon:"□",title:"Extract Pages",desc:"Create a PDF from selected pages.",accept:".pdf",endpoint:"/api/pdf/extract-pages",tag:"Edit"},
{id:"pdfjpg",icon:"▣",title:"PDF to JPG",desc:"Render PDF pages as JPG images in a ZIP.",accept:".pdf",endpoint:"/api/pdf/pdf-to-jpg",tag:"Convert"},
{id:"jpgpdf",icon:"▤",title:"JPG to PDF",desc:"Turn one or more images into a PDF.",multi:true,accept:"image/jpeg,image/png",endpoint:"/api/pdf/jpg-to-pdf",tag:"Convert"}
];
let current=null,files=[];
const $=s=>document.querySelector(s),grid=$("#grid"),workspace=$("#workspace"),input=$("#fileInput"),list=$("#fileList"),options=$("#options"),status=$("#status"),dropZone=$("#dropZone");
function renderTools(q=""){grid.innerHTML="";const found=tools.filter(t=>(t.title+" "+t.desc+" "+t.tag).toLowerCase().includes(q.toLowerCase()));found.forEach(t=>{const el=document.createElement("article");el.className="tool";el.innerHTML=`<div class="icon">${t.icon}</div><h3>${t.title}</h3><p>${t.desc}</p><span class="tool-tag">${t.tag}</span>`;el.onclick=()=>openTool(t);grid.appendChild(el)});if(!found.length)grid.innerHTML='<div style="grid-column:1/-1;text-align:center;padding:40px;color:var(--muted)">No matching tools found.</div>'}
renderTools();$("#search").oninput=e=>renderTools(e.target.value);
$("#themeBtn").onclick=()=>{document.body.classList.toggle("dark");localStorage.setItem("pdf-theme",document.body.classList.contains("dark")?"dark":"light")};if(localStorage.getItem("pdf-theme")==="dark")document.body.classList.add("dark");
function openTool(t){current=t;files=[];input.value="";status.textContent="";workspace.classList.remove("hidden");$("#tools").classList.add("hidden");$("#how").classList.add("hidden");$("#about").classList.add("hidden");$("#toolEyebrow").textContent=t.tag.toUpperCase();$("#toolTitle").textContent=t.title;$("#uploadTitle").textContent=t.multi?"Drop your files here":"Drop your file here";$("#uploadHint").textContent=t.multi?"Choose multiple files or drag them here":"Choose a file or drag it here";input.multiple=!!t.multi;input.accept=t.accept;options.innerHTML="";if(t.id==="split")options.innerHTML='<label>Start page<input id="from" type="number" min="1" value="1"></label><label>End page<input id="to" type="number" min="1" value="1"></label>';if(t.id==="rotate")options.innerHTML='<label>Rotation<select id="degrees"><option value="90">90°</option><option value="180">180°</option><option value="270">270°</option></select></label>';if(t.id==="delete"||t.id==="extract")options.innerHTML='<label>Pages (example: 1,3,5-7)<input id="pages" placeholder="1,3,5-7"></label>';renderFiles();window.scrollTo({top:workspace.offsetTop-90,behavior:"smooth"})}
$("#choose").onclick=()=>input.click();input.onchange=()=>{files=[...input.files];renderFiles()};
["dragenter","dragover"].forEach(e=>dropZone.addEventListener(e,ev=>{ev.preventDefault();dropZone.classList.add("dragover")}));["dragleave","drop"].forEach(e=>dropZone.addEventListener(e,ev=>{ev.preventDefault();dropZone.classList.remove("dragover")}));dropZone.addEventListener("drop",ev=>{if(!current)return;const incoming=[...ev.dataTransfer.files];files=current.multi?incoming:incoming.slice(0,1);renderFiles()});
function renderFiles(){list.innerHTML=files.map(f=>`<div class="file"><span>${escapeHtml(f.name)}</span><small>${(f.size/1024/1024).toFixed(2)} MB</small></div>`).join("")}
function escapeHtml(s){return s.replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
$("#back").onclick=()=>{workspace.classList.add("hidden");$("#tools").classList.remove("hidden");$("#how").classList.remove("hidden");$("#about").classList.remove("hidden");window.scrollTo({top:$("#tools").offsetTop-75,behavior:"smooth"})};
$("#process").onclick=async()=>{if(!files.length){status.textContent="Please choose a file first.";return}if((current.id==="merge"||current.id==="jpgpdf")&&files.length<2){status.textContent=current.id==="merge"?"Choose at least two PDFs to merge.":"Choose at least one image.";if(current.id==="merge")return}const btn=$("#process");btn.disabled=true;status.textContent="Processing your file…";const fd=new FormData();const field=current.multi?"files":"file";files.forEach(f=>fd.append(field,f));if(current.id==="split"){fd.append("from",$("#from").value);fd.append("to",$("#to").value)}if(current.id==="rotate")fd.append("degrees",$("#degrees").value);if(current.id==="delete"||current.id==="extract")fd.append("pages",$("#pages").value);try{const res=await fetch(api(current.endpoint),{method:"POST",body:fd});if(!res.ok){const j=await res.json().catch(()=>({}));throw new Error(j.error||`Processing failed (${res.status})`)}const blob=await res.blob(),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=res.headers.get("Content-Disposition")?.match(/filename="([^"]+)"/)?.[1]||"result.pdf";document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);status.textContent="✓ Done — your file is ready to download."}catch(e){status.textContent="Something went wrong: "+e.message}finally{btn.disabled=false}};
